### ISSUE TITLE
CityPop/RoomKeyed test dao() fails:  expected:<BERLIN> but was:<VADUZ>

### ISSUE THREAD

**Issue by jimandreas** [commonsguy/cw-androidarch#1]
The `dao()` androidTest in `CityPop/RoomKeyed` fails with the following error:

    java.lang.AssertionError: expected:<BERLIN> but was:<VADUZ>

The root cause for this problem appears to be that the `beforeByPopulation` sort is ASC (ascending) instead of matching the other DESC (descending) sorts.   This it places VADUZ, the capital of Lichtenstein, at 5.5K population near the top.

Changing the sort order for `beforeByPopulation` to DESC fixes this issue, and the test passes.

**Comment by commonsguy** [comment]
`RoomKeyed` was an inadvertent commit to the repo. It's not covered in the book and is not ready for use, in part because of the problem that you cited.

**Comment by jimandreas** [comment]
Thanks for the update.   And thanks for helping explain and illustrate all the new AndroidArch developments.   It is quite the departure from the old Content Provider structure!

**Comment by commonsguy** [comment]
Addressed in v0.6 -- thanks!
