### ISSUE TITLE
Error:(17, 30) error: cannot find symbol class ViewModelProviders

### ISSUE THREAD

**Issue by esoxjem** [commonsguy/cw-androidarch#3]
I'm unable to figure out why this class is missing 🤔 

https://github.com/commonsguy/cw-androidarch/blob/master/ToDo/MVI/app/src/main/java/com/commonsware/android/todo/ui/AbstractRosterFragment.java#L17

**Comment by commonsguy** [comment]
Ah, I just ran into that the other day. [Google botched the dependencies, IMHO](https://issuetracker.google.com/issues/73334551), though Google disagrees. I screwed up when I upgraded to the newer dependencies, which caused this problem, which I didn't catch before publication of Version 0.8.

Add `android.arch.lifecycle:extensions:1.1.0` as a dependency, and you should be good to go.

**Comment by esoxjem** [comment]
Yes, this seems and Google says it's the expected behaviour. Quite strange. Anyway, adding `extensions` fixes the issue for now. Thanks!

**Comment by hakeemtunde** [comment]
@commonsguy this also works for me. thanks
