### ISSUE TITLE
EditFragment validation

### ISSUE THREAD

**Issue by sanisloandras** [commonsguy/cw-androidarch#4]
Hello!
I really liked this sample project, and this is not really an issue, more like a question. I just don't know where else could I discuss it...

The 1st question is:
When we create a new todo item, all the validation and error handling is in the EditFragment.
(https://github.com/commonsguy/cw-androidarch/blob/v0.8/ToDo/MVI/app/src/main/java/com/commonsware/android/todo/ui/EditFragment.java#L131-L162)
Wouldn't it be better to move it to the Controller class, and return an Result.AddFailed object if the validation failes?

2: All the CURD methods for todo's return void in the Controlles and TodoRepository classes. What if I have HTTP Requests which return some RxJava stream types like Single, Completable? Where and when should I subscribe to them?

**Comment by commonsguy** [comment]
> I just don't know where else could I discuss it...

[Subscribers](https://commonsware.com/warescription) not only have access to [the book that describes this project](https://commonsware.com/AndroidArch), but also have access to support resources such as "office hours" chats.

> Wouldn't it be better to move it to the Controller class, and return an Result.AddFailed object if the validation failes?

IMHO, no, for basic validation. If the validation requires I/O &mdash; say, for example, you need to check against some data on the server &mdash; then handling that validation in the repository and including that in results through the MVI flow is reasonable. For things that the view can handle totally on its own &mdash; such as "is this field empty?" &mdash; have the view take care of it.

> What if I have HTTP Requests which return some RxJava stream types like Single, Completable? Where and when should I subscribe to them?

For "mainstream" data &mdash; such as REST requests for model data &mdash; I would use synchronous APIs in the repository. If you have no choice but to use a reactive API, my guess is that the repository would be the subscriber.
