### ISSUE TITLE
Dependency Injection chapter?

### ISSUE THREAD

**Issue by SAGARSURI** [commonsguy/cw-androidarch#7]
Will you be adding a dependency injection like `Dagger 2` or `Koin` chapter in any of your ebooks? It would be great as there is no good articles or courses out there that can explain dependency injection in a clear and complete way.

**Comment by commonsguy** [comment]
I will be covering Koin (kovering Koin? :smile:) in *Elements of Android Jetpack* and *Exploring Android* in the coming months.
